# Generated by Django 5.1.6 on 2025-03-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfcdeblocagesmiseenplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='agreementdate',
            field=models.DateField(db_column='AGREEMENTDATE'),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='bankcode',
            field=models.CharField(db_column='BANKCODE', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='capitalnominal',
            field=models.CharField(db_column='CAPITALNOMINAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='cdate',
            field=models.DateField(db_column='CDATE'),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='clientcode',
            field=models.CharField(db_column='CLIENTCODE', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='datefirstallotement',
            field=models.DateField(db_column='DATEFIRSTALLOTEMENT'),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='ech_premi',
            field=models.CharField(db_column='ECH_PREMI', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='enddate',
            field=models.DateField(db_column='ENDDATE'),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='externalrib',
            field=models.CharField(db_column='EXTERNALRIB', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='externalribbankcode',
            field=models.CharField(db_column='EXTERNALRIBBANKCODE', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='franchiseduration',
            field=models.CharField(db_column='FRANCHISEDURATION', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='fullname',
            field=models.CharField(db_column='FULLNAME', max_length=255),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='maxterm',
            field=models.CharField(db_column='MAXTERM', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='productcode',
            field=models.CharField(db_column='PRODUCTCODE', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='reference',
            field=models.CharField(db_column='REFERENCE', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='rib',
            field=models.CharField(db_column='RIB', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='startdate',
            field=models.DateField(db_column='STARTDATE'),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='udate',
            field=models.DateField(db_column='UDATE'),
        ),
        migrations.AlterField(
            model_name='dossier_de_pret',
            name='unitcode',
            field=models.CharField(db_column='UNITCODE', max_length=100, primary_key=True, serialize=False),
        ),
    ]
